Repository beyond-sw-camp/be06-2nd-FIIIIIVE-ZIP_POP, pull requests merged in 2024-07, with the labels that each got.

#52 [Feat] POPUP_001 완료 POPUP_002 완료
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/fiiiiive/.DS_Store
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStore.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreService.java
  src/main/java/com/fiiiiive/zippop/popup_store/req/PopupStoreReq.java
  src/main/java/com/fiiiiive/zippop/popup_store/res/PopupStoreRes.java
Labels: backend

#53 [Feat]GOODS_001 완료, GOODS_002 완료
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoods.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsRepository.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_goods/req/PopupGoodsReq.java
  src/main/java/com/fiiiiive/zippop/popup_goods/res/PopupGoodsRes.java
Labels: backend

#54 [Feat] POPUP_004 완료
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReview.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewRepository.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewService.java
  src/main/java/com/fiiiiive/zippop/popup_review/req/PopupReviewReq.java
  src/main/java/com/fiiiiive/zippop/popup_review/res/PopupReviewRes.java
Labels: backend

#55 [Feat] PAY_003 완료
  build.gradle
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseException.java
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseResponse.java
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseResponseStatus.java
  src/main/java/com/fiiiiive/zippop/config/PortoneConfig.java
  src/main/java/com/fiiiiive/zippop/config/SecurityConfig.java
  src/main/java/com/fiiiiive/zippop/member/CustomUserDetailService.java
  src/main/java/com/fiiiiive/zippop/member/model/CustomUserDetails.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersController.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersDetailRepository.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersRepository.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersService.java
  src/main/java/com/fiiiiive/zippop/orders/model/Orders.java
  src/main/java/com/fiiiiive/zippop/orders/model/OrdersDetail.java
  src/main/java/com/fiiiiive/zippop/orders/model/response/GetOrdersRes.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoods.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/resources/application.yml
Labels: backend

#57 [Feat] PAY_003 수정
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseException.java
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseResponse.java
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/common/baseresponse/BaseResponseStatus.java
  src/main/java/com/fiiiiive/zippop/config/SecurityConfig.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersController.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersService.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
Labels: backend

#59 [Feat] CUSER_001 수정, CUSER_002 수정, CUSER_003 수정, BUSER_001 수정, BUSER_…
  build.gradle
  src/main/java/com/fiiiiive/zippop/common/exception/GlobalExceptionHandler.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/config/SecurityConfig.java
  src/main/java/com/fiiiiive/zippop/config/filter/ExceptionFilter.java
  src/main/java/com/fiiiiive/zippop/config/filter/JwtFilter.java
  src/main/java/com/fiiiiive/zippop/config/filter/LoginFilter.java
  src/main/java/com/fiiiiive/zippop/member/CompanyRepository.java
  src/main/java/com/fiiiiive/zippop/member/CustomUserDetailService.java
  src/main/java/com/fiiiiive/zippop/member/EmailVerify.java
  src/main/java/com/fiiiiive/zippop/member/EmailVerifyService.java
  src/main/java/com/fiiiiive/zippop/member/MemberController.java
  src/main/java/com/fiiiiive/zippop/member/MemberService.java
  src/main/java/com/fiiiiive/zippop/member/model/Company.java
  src/main/java/com/fiiiiive/zippop/member/model/Customer.java
  src/main/java/com/fiiiiive/zippop/member/model/request/PostLoginReq.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersRepository.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/request/PopupGoodsReq.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/response/PopupGoodsRes.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewService.java
  src/main/java/com/fiiiiive/zippop/popup_review/model/request/PopupReviewReq.java
  src/main/java/com/fiiiiive/zippop/popup_review/model/response/PopupReviewRes.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreService.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/request/PopupStoreReq.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/response/PopupStoreRes.java
  src/main/java/com/fiiiiive/zippop/post/PostController.java
  src/main/java/com/fiiiiive/zippop/post/PostService.java
  src/main/java/com/fiiiiive/zippop/post/model/request/PostReq.java
  src/main/java/com/fiiiiive/zippop/post/model/response/PostRes.java
  src/main/java/com/fiiiiive/zippop/test/TestController.java
Labels: backend

#60 [Feat] POPUP_001 성능개선, GOODS_002 성능개선, POPUP_004 성능개선
  src/main/java/com/fiiiiive/zippop/config/SecurityConfig.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsRepository.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/request/CreatePopupGoodsReq.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/response/GetPopupGoodsRes.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/response/PopupGoodsRes.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewRepository.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewService.java
  src/main/java/com/fiiiiive/zippop/popup_review/model/request/CreatePopupReviewReq.java
  src/main/java/com/fiiiiive/zippop/popup_review/model/response/GetPopupReviewRes.java
  src/main/java/com/fiiiiive/zippop/popup_review/model/response/PopupReviewRes.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreService.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/request/CreatePopupStoreReq.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/response/GetPopupStoreRes.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/response/PopupStoreRes.java
  src/main/java/com/fiiiiive/zippop/post/PostController.java
  src/main/java/com/fiiiiive/zippop/post/PostRepository.java
  src/main/java/com/fiiiiive/zippop/post/PostService.java
  src/main/java/com/fiiiiive/zippop/post/model/request/CreatePostReq.java
  src/main/java/com/fiiiiive/zippop/post/model/response/GetPostRes.java
  src/main/java/com/fiiiiive/zippop/post/model/response/PostRes.java
  src/main/resources/application.yml
Labels: backend

#62 [Feat] PAY_003 완료
  src/main/java/com/fiiiiive/zippop/common/exception/BaseException.java
  src/main/java/com/fiiiiive/zippop/common/exception/GlobalExceptionHandler.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersController.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersService.java
  src/main/java/com/fiiiiive/zippop/orders/model/Orders.java
  src/main/java/com/fiiiiive/zippop/orders/model/response/GetOrdersRes.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsRepository.java
Labels: backend

#66 [Feat] Cuser_010 완료 [Fix] Fix_001 완료 [Refactor] 001 완료
  src/main/java/com/fiiiiive/zippop/cart/CartController.java
  src/main/java/com/fiiiiive/zippop/cart/CartRepository.java
  src/main/java/com/fiiiiive/zippop/cart/CartService.java
  src/main/java/com/fiiiiive/zippop/cart/model/Cart.java
  src/main/java/com/fiiiiive/zippop/cart/model/request/CreateCartReq.java
  src/main/java/com/fiiiiive/zippop/cart/model/response/CountCartRes.java
  src/main/java/com/fiiiiive/zippop/cart/model/response/CreateCartRes.java
  src/main/java/com/fiiiiive/zippop/cart/model/response/GetCartRes.java
  src/main/java/com/fiiiiive/zippop/chat/ChatService.java
  src/main/java/com/fiiiiive/zippop/common/annotation/ExeTimer.java
  src/main/java/com/fiiiiive/zippop/common/exception/BaseException.java
  src/main/java/com/fiiiiive/zippop/common/exception/GlobalExceptionHandler.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/config/filter/ExceptionFilter.java
  src/main/java/com/fiiiiive/zippop/config/filter/JwtFilter.java
  src/main/java/com/fiiiiive/zippop/member/CustomUserDetailService.java
  src/main/java/com/fiiiiive/zippop/member/EmailVerifyRepository.java
  src/main/java/com/fiiiiive/zippop/member/EmailVerifyService.java
  src/main/java/com/fiiiiive/zippop/member/MemberController.java
  src/main/java/com/fiiiiive/zippop/member/MemberService.java
  src/main/java/com/fiiiiive/zippop/member/model/Company.java
  src/main/java/com/fiiiiive/zippop/member/model/Customer.java
  src/main/java/com/fiiiiive/zippop/member/model/EmailVerify.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersController.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersService.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewService.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/PopupStore.java
  src/main/java/com/fiiiiive/zippop/post/PostController.java
  src/main/java/com/fiiiiive/zippop/utils/ExecutionTimer.java
  src/main/java/com/fiiiiive/zippop/utils/JwtUtil.java
  src/main/resources/application.yml
Labels: bug, backend, refactor

#67 [Feat] CUSER_006 완료, CUSER_010 수정, BUSER_003 수정, CUSER_001 수정
  src/main/java/com/fiiiiive/zippop/cart/CartController.java
  src/main/java/com/fiiiiive/zippop/cart/CartRepository.java
  src/main/java/com/fiiiiive/zippop/cart/CartService.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/favorite/FavoriteController.java
  src/main/java/com/fiiiiive/zippop/favorite/FavoriteRepository.java
  src/main/java/com/fiiiiive/zippop/favorite/FavoriteService.java
  src/main/java/com/fiiiiive/zippop/favorite/model/Favorite.java
  src/main/java/com/fiiiiive/zippop/favorite/model/response/GetFavoriteRes.java
  src/main/java/com/fiiiiive/zippop/member/MemberController.java
  src/main/java/com/fiiiiive/zippop/member/MemberService.java
  src/main/java/com/fiiiiive/zippop/member/ProfileService.java
  src/main/java/com/fiiiiive/zippop/member/model/Customer.java
  src/main/java/com/fiiiiive/zippop/popup_goods/model/PopupGoods.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/PopupStore.java
  src/main/resources/application.yml
Labels: bug, backend, refactor

#68 [Feat] CUSER_009 완료, BUSER_007 완료
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/member/EmailVerifyRepository.java
  src/main/java/com/fiiiiive/zippop/member/MemberController.java
  src/main/java/com/fiiiiive/zippop/member/MemberService.java
  src/main/java/com/fiiiiive/zippop/member/model/response/PostSignupRes.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
Labels: backend

#70 [Feat] COMMENT_001 완료 COMMENT_002 완료
  src/main/java/com/fiiiiive/zippop/comment/Comment.java
  src/main/java/com/fiiiiive/zippop/comment/CommentController.java
  src/main/java/com/fiiiiive/zippop/comment/CommentRepository.java
  src/main/java/com/fiiiiive/zippop/comment/CommentService.java
  src/main/java/com/fiiiiive/zippop/comment/model/request/CreateCommentReq.java
  src/main/java/com/fiiiiive/zippop/comment/model/response/GetCommentRes.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
Labels: backend

#72 [Feat] PAY_001 완료, PAY_002 완료, PAY_003 성능개선
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersController.java
  src/main/java/com/fiiiiive/zippop/orders/OrdersService.java
  src/main/java/com/fiiiiive/zippop/orders/model/response/GetOrdersRes.java
Labels: backend

#73 [Refactor]COMMENT_002 수정
  src/main/java/com/fiiiiive/zippop/comment/CommentController.java
  src/main/java/com/fiiiiive/zippop/comment/CommentRepository.java
  src/main/java/com/fiiiiive/zippop/comment/CommentService.java
  src/main/java/com/fiiiiive/zippop/comment/model/Comment.java
  src/main/java/com/fiiiiive/zippop/member/model/Customer.java
  src/main/java/com/fiiiiive/zippop/post/model/Post.java
Labels: backend

#74 Feature/paging
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/fiiiiive/.DS_Store
  src/main/java/com/fiiiiive/zippop/.DS_Store
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsRepository.java
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsService.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewRepository.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewService.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreService.java
  src/main/java/com/fiiiiive/zippop/post/PostController.java
  src/main/java/com/fiiiiive/zippop/post/PostRepository.java
  src/main/java/com/fiiiiive/zippop/post/PostService.java
Labels: enhancement, backend, refactor

#75 [Fix] POPUP_001 수정, POST_002 수정
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreRepository.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreService.java
  src/main/java/com/fiiiiive/zippop/post/PostController.java
Labels: bug, backend

#77 [Feat] RESERVE_001 완료, RESERVE_002 완료, RESERVE_003 완료
  build.gradle
  src/main/java/com/fiiiiive/zippop/common/exception/GlobalExceptionHandler.java
  src/main/java/com/fiiiiive/zippop/common/responses/BaseResponseMessage.java
  src/main/java/com/fiiiiive/zippop/config/RedisConfig.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/PopupReserveController.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/PopupReserveRepository.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/PopupReserveService.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/model/PopupReserve.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/model/request/CreatePopupReserveReq.java
  src/main/java/com/fiiiiive/zippop/popup_reserve/model/response/CreatePopupReserveRes.java
  src/main/java/com/fiiiiive/zippop/popup_store/model/PopupStore.java
  src/main/java/com/fiiiiive/zippop/utils/JwtUtil.java
  src/main/java/com/fiiiiive/zippop/utils/RedisUtil.java
  src/main/resources/application.yml
Labels: backend

#78 [Refactor] POPUP_001 수정, GOODS_002 수정
  .DS_Store
  src/main/java/com/fiiiiive/zippop/popup_goods/PopupGoodsController.java
  src/main/java/com/fiiiiive/zippop/popup_review/PopupReviewController.java
  src/main/java/com/fiiiiive/zippop/popup_store/PopupStoreController.java
Labels: backend
